package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Primary Brand Accents
val AccentCyan = Color(0xFF00E5FF)
val AccentCobalt = Color(0xFF2979FF)
val AccentEmerald = Color(0xFF00E676)
val AccentAmber = Color(0xFFFFB300)
val AccentCoral = Color(0xFFFF5252)

// Dark Theme (Deep neutral black with elevated charcoal surfaces)
val DarkBackground = Color(0xFF0D1117)
val DarkSurface = Color(0xFF161B22)
val DarkSurfaceVariant = Color(0xFF21262D)
val DarkBorder = Color(0xFF30363D)
val DarkTextPrimary = Color(0xFFF0F6FC)
val DarkTextSecondary = Color(0xFF8B949E)

// Graphite Theme (Sophisticated zinc/gray)
val GraphiteBackground = Color(0xFF121316)
val GraphiteSurface = Color(0xFF1C1D22)
val GraphiteSurfaceVariant = Color(0xFF262830)
val GraphiteBorder = Color(0xFF363945)
val GraphiteTextPrimary = Color(0xFFF4F4F5)
val GraphiteTextSecondary = Color(0xFFA1A1AA)
val GraphiteAccent = Color(0xFF38BDF8)

// Midnight Theme (Deep oceanic blue-black)
val MidnightBackground = Color(0xFF060913)
val MidnightSurface = Color(0xFF0F172A)
val MidnightSurfaceVariant = Color(0xFF1E293B)
val MidnightBorder = Color(0xFF334155)
val MidnightTextPrimary = Color(0xFFF8FAFC)
val MidnightTextSecondary = Color(0xFF94A3B8)
val MidnightAccent = Color(0xFF60A5FA)

// Aurora Theme (Muted dark slate with subtle cyan/teal)
val AuroraBackground = Color(0xFF081214)
val AuroraSurface = Color(0xFF0E1F24)
val AuroraSurfaceVariant = Color(0xFF162E35)
val AuroraBorder = Color(0xFF20424C)
val AuroraTextPrimary = Color(0xFFECFEFF)
val AuroraTextSecondary = Color(0xFF6EE7B7)
val AuroraAccent = Color(0xFF2DD4BF)

// Cream Theme (Warm minimalist luxury)
val CreamBackground = Color(0xFFF9F7F2)
val CreamSurface = Color(0xFFFFFFFF)
val CreamSurfaceVariant = Color(0xFFEFECE6)
val CreamBorder = Color(0xFFDDD8CE)
val CreamTextPrimary = Color(0xFF1C1917)
val CreamTextSecondary = Color(0xFF78716C)
val CreamAccent = Color(0xFFB45309)

// Light Theme (Clean modern neutral light)
val LightBackground = Color(0xFFF8FAFC)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightBorder = Color(0xFFE2E8F0)
val LightTextPrimary = Color(0xFF0F172A)
val LightTextSecondary = Color(0xFF64748B)
val LightAccent = Color(0xFF0284C7)

// Cyberpunk Neon Theme (Electric purple & cyber yellow)
val CyberpunkBackground = Color(0xFF0E051C)
val CyberpunkSurface = Color(0xFF190B30)
val CyberpunkSurfaceVariant = Color(0xFF28134C)
val CyberpunkBorder = Color(0xFF452080)
val CyberpunkTextPrimary = Color(0xFFFFF0FA)
val CyberpunkTextSecondary = Color(0xFFD4B8E8)
val CyberpunkAccent = Color(0xFFFFEA00)
val CyberpunkSecondary = Color(0xFFE040FB)

// Sunset Glow Theme (Twilight indigo & warm radiant amber)
val SunsetBackground = Color(0xFF120C1C)
val SunsetSurface = Color(0xFF1E142E)
val SunsetSurfaceVariant = Color(0xFF2D1E45)
val SunsetBorder = Color(0xFF452E6A)
val SunsetTextPrimary = Color(0xFFFFF4ED)
val SunsetTextSecondary = Color(0xFFD2B4DE)
val SunsetAccent = Color(0xFFFF6D00)
val SunsetSecondary = Color(0xFFFFAB40)

// Emerald Matrix Theme (Deep obsidian & luminous matrix green)
val EmeraldBackground = Color(0xFF041008)
val EmeraldSurface = Color(0xFF0A1F12)
val EmeraldSurfaceVariant = Color(0xFF102E1B)
val EmeraldBorder = Color(0xFF1B492B)
val EmeraldTextPrimary = Color(0xFFE8F5E9)
val EmeraldTextSecondary = Color(0xFFA5D6A7)
val EmeraldAccent = Color(0xFF00E676)
val EmeraldSecondary = Color(0xFF69F0AE)

// Oceanic Breeze Theme (Deep marine blue & electric turquoise)
val OceanicBackground = Color(0xFF04111D)
val OceanicSurface = Color(0xFF091E32)
val OceanicSurfaceVariant = Color(0xFF0F2D4A)
val OceanicBorder = Color(0xFF184570)
val OceanicTextPrimary = Color(0xFFE0F7FA)
val OceanicTextSecondary = Color(0xFF80DEEA)
val OceanicAccent = Color(0xFF00E5FF)
val OceanicSecondary = Color(0xFF26C6DA)

// AMOLED Pure Black Theme (True #000000 black for OLED efficiency)
val AmoledBackground = Color(0xFF000000)
val AmoledSurface = Color(0xFF000000)
val AmoledSurfaceVariant = Color(0xFF111111)
val AmoledBorder = Color(0xFF262626)
val AmoledTextPrimary = Color(0xFFFFFFFF)
val AmoledTextSecondary = Color(0xFFA1A1AA)
val AmoledAccent = Color(0xFF38BDF8)
val AmoledSecondary = Color(0xFF00E5FF)

